[2023-11-01 17:47:11,831] {scheduler_job.py:182} INFO - Started process (PID=1210) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:47:11,832] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:47:11,832] {logging_mixin.py:104} INFO - [2023-11-01 17:47:11,832] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:47:12,092] {logging_mixin.py:104} INFO - [2023-11-01 17:47:12,091] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:47:12,092] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:47:12,094] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.265 seconds
[2023-11-01 17:47:42,517] {scheduler_job.py:182} INFO - Started process (PID=1290) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:47:42,517] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:47:42,517] {logging_mixin.py:104} INFO - [2023-11-01 17:47:42,517] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:47:42,785] {logging_mixin.py:104} INFO - [2023-11-01 17:47:42,784] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:47:42,785] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:47:42,798] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.283 seconds
[2023-11-01 17:48:13,271] {scheduler_job.py:182} INFO - Started process (PID=1371) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:48:13,271] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:48:13,271] {logging_mixin.py:104} INFO - [2023-11-01 17:48:13,271] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:48:13,507] {logging_mixin.py:104} INFO - [2023-11-01 17:48:13,507] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:48:13,507] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:48:13,521] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.251 seconds
[2023-11-01 17:48:43,978] {scheduler_job.py:182} INFO - Started process (PID=1442) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:48:43,978] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:48:43,978] {logging_mixin.py:104} INFO - [2023-11-01 17:48:43,978] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:48:44,221] {logging_mixin.py:104} INFO - [2023-11-01 17:48:44,220] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:48:44,221] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:48:44,223] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.247 seconds
[2023-11-01 17:49:14,584] {scheduler_job.py:182} INFO - Started process (PID=1523) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:49:14,584] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:49:14,585] {logging_mixin.py:104} INFO - [2023-11-01 17:49:14,584] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:49:14,832] {logging_mixin.py:104} INFO - [2023-11-01 17:49:14,832] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:49:14,832] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:49:14,835] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.252 seconds
[2023-11-01 17:49:45,382] {scheduler_job.py:182} INFO - Started process (PID=1603) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:49:45,382] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:49:45,382] {logging_mixin.py:104} INFO - [2023-11-01 17:49:45,382] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:49:45,612] {logging_mixin.py:104} INFO - [2023-11-01 17:49:45,611] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:49:45,612] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:49:45,624] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.244 seconds
[2023-11-01 17:50:15,980] {scheduler_job.py:182} INFO - Started process (PID=1683) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:50:15,981] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:50:15,981] {logging_mixin.py:104} INFO - [2023-11-01 17:50:15,981] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:50:16,213] {logging_mixin.py:104} INFO - [2023-11-01 17:50:16,213] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:50:16,214] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:50:16,217] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.238 seconds
[2023-11-01 17:50:46,699] {scheduler_job.py:182} INFO - Started process (PID=1764) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:50:46,699] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:50:46,699] {logging_mixin.py:104} INFO - [2023-11-01 17:50:46,699] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:50:46,961] {logging_mixin.py:104} INFO - [2023-11-01 17:50:46,961] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:50:46,962] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:50:46,964] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.267 seconds
[2023-11-01 17:51:17,473] {scheduler_job.py:182} INFO - Started process (PID=1835) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:51:17,473] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:51:17,473] {logging_mixin.py:104} INFO - [2023-11-01 17:51:17,473] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:51:17,751] {logging_mixin.py:104} INFO - [2023-11-01 17:51:17,750] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:51:17,751] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:51:17,765] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.293 seconds
[2023-11-01 17:51:48,389] {scheduler_job.py:182} INFO - Started process (PID=1916) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:51:48,389] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:51:48,389] {logging_mixin.py:104} INFO - [2023-11-01 17:51:48,389] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:51:48,709] {logging_mixin.py:104} INFO - [2023-11-01 17:51:48,708] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:51:48,709] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:51:48,712] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.325 seconds
[2023-11-01 17:52:19,610] {scheduler_job.py:182} INFO - Started process (PID=1997) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:52:19,610] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:52:19,610] {logging_mixin.py:104} INFO - [2023-11-01 17:52:19,610] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:52:19,941] {logging_mixin.py:104} INFO - [2023-11-01 17:52:19,940] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:52:19,941] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:52:19,954] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.347 seconds
[2023-11-01 17:52:50,713] {scheduler_job.py:182} INFO - Started process (PID=2078) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:52:50,714] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:52:50,715] {logging_mixin.py:104} INFO - [2023-11-01 17:52:50,714] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:52:51,114] {logging_mixin.py:104} INFO - [2023-11-01 17:52:51,113] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:52:51,114] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:52:51,128] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.418 seconds
[2023-11-01 17:53:21,819] {scheduler_job.py:182} INFO - Started process (PID=2149) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:53:21,819] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:53:21,820] {logging_mixin.py:104} INFO - [2023-11-01 17:53:21,820] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:53:22,112] {logging_mixin.py:104} INFO - [2023-11-01 17:53:22,111] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:53:22,112] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:53:22,115] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.297 seconds
[2023-11-01 17:53:52,577] {scheduler_job.py:182} INFO - Started process (PID=2230) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:53:52,578] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:53:52,578] {logging_mixin.py:104} INFO - [2023-11-01 17:53:52,578] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:53:52,909] {logging_mixin.py:104} INFO - [2023-11-01 17:53:52,908] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:53:52,909] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:53:52,924] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.349 seconds
[2023-11-01 17:54:23,339] {scheduler_job.py:182} INFO - Started process (PID=2311) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:54:23,340] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:54:23,340] {logging_mixin.py:104} INFO - [2023-11-01 17:54:23,340] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:54:23,681] {logging_mixin.py:104} INFO - [2023-11-01 17:54:23,680] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weathermap_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weathermap_dag.py", line 14, in <module>
    WEATHER_API_ENDPOINT = '/data/2.5/weather?q=Portland&APPID=' + Variable.get("weathermap_api_key")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable weathermap_api_key does not exist'
[2023-11-01 17:54:23,682] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:54:23,685] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.348 seconds
[2023-11-01 17:54:29,764] {scheduler_job.py:182} INFO - Started process (PID=2343) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:54:29,765] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:54:29,765] {logging_mixin.py:104} INFO - [2023-11-01 17:54:29,765] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:54:30,020] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:54:30,796] {logging_mixin.py:104} INFO - [2023-11-01 17:54:30,795] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:54:30,800] {logging_mixin.py:104} INFO - [2023-11-01 17:54:30,799] {dag.py:1852} INFO - Creating ORM DAG for weather_dag
[2023-11-01 17:54:30,803] {logging_mixin.py:104} INFO - [2023-11-01 17:54:30,803] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:54:30,807] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 1.045 seconds
[2023-11-01 17:55:01,650] {scheduler_job.py:182} INFO - Started process (PID=2417) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:55:01,650] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:55:01,650] {logging_mixin.py:104} INFO - [2023-11-01 17:55:01,650] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:55:01,896] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:55:01,906] {logging_mixin.py:104} INFO - [2023-11-01 17:55:01,906] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:55:01,914] {logging_mixin.py:104} INFO - [2023-11-01 17:55:01,914] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:55:01,918] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.270 seconds
[2023-11-01 17:55:32,741] {scheduler_job.py:182} INFO - Started process (PID=2498) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:55:32,741] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:55:32,742] {logging_mixin.py:104} INFO - [2023-11-01 17:55:32,742] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:55:32,996] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:55:33,005] {logging_mixin.py:104} INFO - [2023-11-01 17:55:33,005] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:55:33,013] {logging_mixin.py:104} INFO - [2023-11-01 17:55:33,013] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:55:33,027] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.288 seconds
[2023-11-01 17:56:03,561] {scheduler_job.py:182} INFO - Started process (PID=2579) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:56:03,561] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:56:03,561] {logging_mixin.py:104} INFO - [2023-11-01 17:56:03,561] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:56:03,793] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:56:03,802] {logging_mixin.py:104} INFO - [2023-11-01 17:56:03,802] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:56:03,810] {logging_mixin.py:104} INFO - [2023-11-01 17:56:03,810] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:56:03,812] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.253 seconds
[2023-11-01 17:56:34,379] {scheduler_job.py:182} INFO - Started process (PID=2660) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:56:34,380] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:56:34,380] {logging_mixin.py:104} INFO - [2023-11-01 17:56:34,380] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:56:34,616] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:56:34,625] {logging_mixin.py:104} INFO - [2023-11-01 17:56:34,625] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:56:34,632] {logging_mixin.py:104} INFO - [2023-11-01 17:56:34,632] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:56:34,635] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.257 seconds
[2023-11-01 17:57:05,144] {scheduler_job.py:182} INFO - Started process (PID=2741) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:57:05,144] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:57:05,145] {logging_mixin.py:104} INFO - [2023-11-01 17:57:05,145] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:57:05,383] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:57:05,394] {logging_mixin.py:104} INFO - [2023-11-01 17:57:05,394] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:57:05,401] {logging_mixin.py:104} INFO - [2023-11-01 17:57:05,401] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:57:05,405] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.263 seconds
[2023-11-01 17:57:35,972] {scheduler_job.py:182} INFO - Started process (PID=2812) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:57:35,972] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:57:35,972] {logging_mixin.py:104} INFO - [2023-11-01 17:57:35,972] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:57:36,216] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:57:36,225] {logging_mixin.py:104} INFO - [2023-11-01 17:57:36,225] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:57:36,231] {logging_mixin.py:104} INFO - [2023-11-01 17:57:36,231] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:57:36,245] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.275 seconds
[2023-11-01 17:57:47,529] {scheduler_job.py:182} INFO - Started process (PID=2861) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:57:47,529] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:57:47,529] {logging_mixin.py:104} INFO - [2023-11-01 17:57:47,529] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:57:47,782] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:57:47,791] {logging_mixin.py:104} INFO - [2023-11-01 17:57:47,791] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:57:47,797] {logging_mixin.py:104} INFO - [2023-11-01 17:57:47,797] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:57:47,812] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.285 seconds
[2023-11-01 17:58:18,689] {scheduler_job.py:182} INFO - Started process (PID=2944) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:58:18,689] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:58:18,690] {logging_mixin.py:104} INFO - [2023-11-01 17:58:18,690] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:58:18,958] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:58:18,970] {logging_mixin.py:104} INFO - [2023-11-01 17:58:18,970] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:58:18,976] {logging_mixin.py:104} INFO - [2023-11-01 17:58:18,976] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:58:18,991] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.304 seconds
[2023-11-01 17:58:44,424] {scheduler_job.py:182} INFO - Started process (PID=3015) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:58:44,424] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:58:44,425] {logging_mixin.py:104} INFO - [2023-11-01 17:58:44,425] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:58:44,687] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:58:44,769] {logging_mixin.py:104} INFO - [2023-11-01 17:58:44,769] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:58:44,776] {logging_mixin.py:104} INFO - [2023-11-01 17:58:44,776] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:58:44,782] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.359 seconds
[2023-11-01 17:59:15,353] {scheduler_job.py:182} INFO - Started process (PID=3086) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:59:15,354] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:59:15,354] {logging_mixin.py:104} INFO - [2023-11-01 17:59:15,354] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:59:15,623] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:59:15,631] {logging_mixin.py:104} INFO - [2023-11-01 17:59:15,631] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:59:15,637] {logging_mixin.py:104} INFO - [2023-11-01 17:59:15,637] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:59:15,640] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.289 seconds
[2023-11-01 17:59:18,753] {scheduler_job.py:182} INFO - Started process (PID=3124) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:59:18,754] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:59:18,754] {logging_mixin.py:104} INFO - [2023-11-01 17:59:18,754] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:59:19,046] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:59:19,131] {logging_mixin.py:104} INFO - [2023-11-01 17:59:19,131] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:59:19,138] {logging_mixin.py:104} INFO - [2023-11-01 17:59:19,138] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:59:19,150] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.398 seconds
[2023-11-01 17:59:49,672] {scheduler_job.py:182} INFO - Started process (PID=3203) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:59:49,672] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 17:59:49,672] {logging_mixin.py:104} INFO - [2023-11-01 17:59:49,672] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:59:49,952] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 17:59:49,960] {logging_mixin.py:104} INFO - [2023-11-01 17:59:49,960] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 17:59:49,967] {logging_mixin.py:104} INFO - [2023-11-01 17:59:49,967] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 17:59:49,970] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.300 seconds
[2023-11-01 18:00:20,489] {scheduler_job.py:182} INFO - Started process (PID=3275) to work on /opt/airflow/dags/weathermap_dag.py
[2023-11-01 18:00:20,489] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weathermap_dag.py for tasks to queue
[2023-11-01 18:00:20,489] {logging_mixin.py:104} INFO - [2023-11-01 18:00:20,489] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 18:00:20,755] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['weather_dag']) retrieved from /opt/airflow/dags/weathermap_dag.py
[2023-11-01 18:00:20,764] {logging_mixin.py:104} INFO - [2023-11-01 18:00:20,763] {dag.py:1833} INFO - Sync 1 DAGs
[2023-11-01 18:00:20,770] {logging_mixin.py:104} INFO - [2023-11-01 18:00:20,770] {dag.py:2306} INFO - Setting next_dagrun for weather_dag to 2023-10-31 00:00:00+00:00
[2023-11-01 18:00:20,774] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weathermap_dag.py took 0.287 seconds
